name: Gravelbike
favicon: null
layout_spectrum: 0.96623
typography_spectrum: 0.546606826595962
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Road bike efficiency and speed meets off road stability and handling.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#61594e'
    - '#837e74'
    - '#c2b8ae'
  brandStrength: 0.3125
  lightness: 0.08927791006863117
  saturation: 0.1866169024724513
  rhythmicContrast: 0.04061109153553843
purpose: []
