analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.7622431840281934
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.1866169024724513
  brandStrength: 0.2405789496842772
  rhythmicContrast: 0.04061109153553843
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0.08927791006863117
purpose: []
favicon: null
name: Gravelbike
typography_spectrum: 0.546606826595962
