name: Gravelbike
favicon: null
layout_spectrum: 0.92252
typography_spectrum: 0.15309
title: Road bike efficiency and speed meets off road stability and handling.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#61594e'
    - '#837e74'
    - '#c2b8ae'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
