name: Gravelbike
favicon: null
layout_spectrum: 0.7622431840281934
typography_spectrum: 0.546606826595962
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.24057894968427718
  lightness: 0.08927791006863117
  saturation: 0.18661690247245133
  rhythmicContrast: 0.040611091535538435
purpose: []
